package lookup

import "time"

var TimeoutDur time.Duration = 5 * time.Second
var TRANSACTION_TYPE string = "49"
var PROD_CODE string = "12"
var IN_PROGRESS string = "09"
var SUCCESS string = "00"
var GENERALERROR string = "06"
var REDISNOTEXIST string = "101"
var INVALIDUSER string = "102"
var INVALIDPUBLICKEY string = "103"
var RedisExpInSeconds int = 1800
var RedisExpForOnboardingInSeconds int = 1800
var INVALID_SESSIONID string = "31"
var INVALIDPARTNERID string = "104"
var INVALIDUSERID string = "105"
var EMPTYPUBLICKEYPARTNER string = "107"
var ERRORQUERY string = "108"
var ERRORGENERATEKEY string = "109"
var EMPTYSESSIONID string = "110"
var EMPTYPARTNERID string = "111"
var EMPTYTRANSACTIONID string = "112"
var EMPTYSIGNATURE string = "113"
var EMPTYACCOUNTNO string = "114"
var EMPTYCURRENCYCODE string = "115"
var EMPTYDESTACCNO string = "116"
var EMPTYAMOUNT string = "117"
var EMPTYTRANSRESP string = "118"
var EMPTYREMARK string = "119"
var INVALIDTRXID string = "120"
var EMPTYOSID string = "121"
var EMPTYMAJOR string = "122"
var EMPTYMINOR string = "123"
var EMPTYTIMESTAMP string = "124"
var EMPTYREVISION string = "125"
var EMPTYBUILDNUMBER string = "126"
var EMPTYSTARTDATE string = "127"
var EMPTYENDDATE string = "128"
var SERVICEERROR string = "S91"
var FORMATERROR string = "30"
var ERRORREQUEST string = "129"
var SYSTEMMALFUNcTION string = "96"
var DUPLICATETRANSMISSION string = "94"
